"""removes name, email, and content fields from message table

Revision ID: 3cb156e533ed
Revises: e20142faf024
Create Date: 2024-03-13 10:29:42.243815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb156e533ed'
down_revision = 'e20142faf024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('content')
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('content', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
