"""Adds origin column to receivers

Revision ID: 9cd8b8f6f642
Revises: 3cb156e533ed
Create Date: 2024-03-13 11:16:26.675225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd8b8f6f642'
down_revision = '3cb156e533ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receivers', schema=None) as batch_op:
        batch_op.drop_column('origin')

    # ### end Alembic commands ###
